### ISSUE TITLE
Reference sources, images, configs, params by name

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#103]
Currently when referencing sources, images, and configs we use json path based notation: 
```
sources[0].url
```
```
sources[?(@.name=="source-provider")].url
```

It's a much nicer user experience if we can use a more succinct name-based notation:
```
sources.source-provider.url
```
```
sources["source-provider"].url
```

See #73 for more detailed examples.

**Comment by DanieldeR** [comment]
Other items that are in scope of this issue:

* Names need to be non-zero length
* Documentation updates
  * Examples
  * OSS & Commercial Docs

**Comment by DanieldeR** [comment]
As discussed during IPM, we'll be leaving the behind-the-scenes implementation as a list, but refer to them as maps.
