### ISSUE TITLE
Add warning to docs that a SupplyChain has broad permissions

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#105]

**Comment by DanieldeR** [comment]
This should likely be added directly to the readme as well as potentially another page in the documentation to capture security-related items.

**Comment by waciumawanjohi** [comment]
As per @jwntrs Just a note on the main README at Beta release time will be fine.

**Comment by cirocosta** [comment]
done @ https://github.com/vmware-tanzu/cartographer/pull/135
