### ISSUE TITLE
Create RFC for delivery

### ISSUE THREAD

**Issue by DanieldeR** [vmware-tanzu/cartographer#12]
* [x] Get RFC into repository [Stephen Levine]
* [ ] Generate stories from RFC [@squeedee]

Requirements:
https://docs.google.com/document/d/1n0jp0ud7j-6mLzbNNcC0EC5HAgCeDbHs0chFe9iBDsc

**Comment by squeedee** [comment]
@jwntrs please try and copy the existing yaml and rfp info into this issue?

**Comment by jwntrs** [comment]
I just linked to the private doc for now. We can update once we get started on a public RFC.

**Comment by squeedee** [comment]
Stephen Levine will have an RFC ready for us today, and then I'll create initial stories.

**Comment by jwntrs** [comment]
@squeedee I wrote up https://github.com/vmware-tanzu/cartographer/issues/220. Feel free to add/change whatever you want
