### ISSUE TITLE
remove deliverable from crd, move it so it is available for tests

### ISSUE THREAD

**Issue by emmjohnson** [vmware-tanzu/cartographer#130]

**Comment by cirocosta** [comment]
prior art: 

https://github.com/vmware-tanzu/cartographer/blob/9d70a9f630c3350cdc9ef962afed48a3f1c0616a/tests/integration/pipeline_service/testapi/test.go#L25-L33

https://github.com/vmware-tanzu/cartographer/blob/9d70a9f630c3350cdc9ef962afed48a3f1c0616a/Makefile#L19-L22

**Comment by waciumawanjohi** [comment]
This line will likely need to be updated to add the new home of deliverable:
https://github.com/vmware-tanzu/cartographer/blob/40df4f914161d6a042362fb61f1d70a1c8ad9708/kuttl-test.yaml#L20
