### ISSUE TITLE
Provide guidance on system requirements

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#148]
_"I want to be have enough guidance on how to allocate resources for cartographer"_

```gherkin
Given I'm about to install Cartographer
When I finish read the installation guide
Then I feel confident about allocating resources for my system
```

## context

currently, when installing the controller via the configuration that we provide (see ./config/manager), a certain set of memory and cpu get limitted & reserved:

https://github.com/vmware-tanzu/cartographer/blob/d4c3a11548cb4084aedda0453abeebfbcf1c3d67/config/manager/deployment.yaml#L67-L73

while those have been "just fine" based on "that's probably enough", we should aim at least at providing values based on a certain benchmark that we set, as well as provide some clues on how one should go about allocating resources for their system, e.g., making very clear that cartographer is just choreographing other components and that the result of those   other ones acting on changes should be considered.

##

acceptance criteria:

- [ ] documentation updated with sizing guidance
- [ ] a benchmark setup
- [ ] results from running the benchmark posted as a chart of memory and cpu usage as # of workloads scales

**Comment by squeedee** [comment]
Propose:

Submit many workloads, that also trigger many runnables.
Profile with a supposed linear scale (50,100,150... jobs) and see how linearly mem and cpu behave.
Capture for future reference.

## Notes:
* Can use configs or something that does not use3rd party controllers.

**Comment by cirocosta** [comment]
done @ #762 #763
