### ISSUE TITLE
Doc Mirroring

### ISSUE THREAD

**Issue by DanieldeR** [vmware-tanzu/cartographer#160]
Maintaining two sets of documentation is not efficient in the long run. We may want to look into a solution for mirroring the docs. 

## Acceptance Criteria
* Docs that are deployed for the OSS version are also available internally.

**Comment by DanieldeR** [comment]
There may be a Hugo plugin that could take care of this.

**Comment by emmjohnson** [comment]
I asked in slack - https://vmware.slack.com/archives/C01GS5414J3/p1633630874115900

**Comment by emmjohnson** [comment]
Suggestion from Stephen - Keep tap docs specific to how cartographer is used in tap. Link out to cartographer docs from tap as much as possible to not have duplication.

**Comment by DanieldeR** [comment]
Upon further review, this issue no longer necessary.
