### ISSUE TITLE
readme: incomplete `curl` command to retrieve bundle.tar

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#161]
### problem

currently, we indicate that one can fetch the `imgpkg` bundle from GitHub releases with a plain `curl -SOL <url>`, but that's not really true - given that _at the moment_ the repository is private, a token must be provided.

### possible solution 

AFAIR it's possible to do so via a mix of using some form of `Authorization: Bearer <token>` and the api for downloads (just the token + regular URL doesn't work, _I think_) - we could make the readme a bit more complete w/ the addition of a proper command that includes the token (or.. maybe, mention that the `gh` cli is pretty good at doing that? I'd prefer plain `curl` tbh)

**Comment by emmjohnson** [comment]
Repository is no longer private. Closing.
