### ISSUE TITLE
Create secondary Docker config.json

### ISSUE THREAD

**Issue by DanieldeR** [vmware-tanzu/cartographer#167]
in hack/setup we are mutating local docker config - can we create a new config and convince docker to use that?

**Comment by cirocosta** [comment]
I _believe_ it totally doable - I'm sure `ko` would do the right thing (honor `DOCKER_CONFIG`) as it's based on [gccr](https://github.com/google/go-containerregistry/), but I think `imgpkg` is too, so I think _yes_, we can do it 😁 

any suggestions on where should it go? temporary file? a `.gitignore`d json (`docker-config.json`) in the root directory of the repository?

**Comment by cirocosta** [comment]
#218 
#175
