### ISSUE TITLE
github: add pr template

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#189]
### Description of problem

There is not much uniformity in how we describe the changes we're bringing with the PRs we open.

### Proposed solution

```gherkin
Given I have changes
When I open the PR
Then the description box (+ title) is pre-filled with fields that should be included in all PRs
```

### Example

<img width="1172" alt="Screen Shot 2021-10-01 at 11 05 12 AM" src="https://user-images.githubusercontent.com/3574444/135643362-6d2d072b-4cf0-48b4-8bbc-0027eccc5d76.png">

^ opening a PR in concourse/concourse

## Additional Context

under ./CONTRIBUTING.md we have some guidelines around PRs, we should make sure that what we include in the PR template should be aligned with the guidance from CONTRIBUTING.md

**Comment by emmjohnson** [comment]
This is done.
