### ISSUE TITLE
Clarify How to Release

### ISSUE THREAD

**Issue by DanieldeR** [vmware-tanzu/cartographer#190]
Unclear how to cut the release. In the release workflow, the release is actually built under e2e which is not confusing/not obvious.

**Comment by DanieldeR** [comment]
The ask on this issue is to make the GitHub action more explicit and easy to read.

**Comment by idoru** [comment]
Looks like this has already been made into an explicit step in the workflow: https://github.com/vmware-tanzu/cartographer/blob/main/.github/workflows/release.yaml#L61-L68
