### ISSUE TITLE
Complete GitHub community profile checklist

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/cartographer#204]
### Description of problem

Currently, the repo is falling short on three items from the GitHUb community checklist:

https://github.com/vmware-tanzu/cartographer/community

* [x] Description
* [x] PR template
* [x] Repository admins accept content reports

### Proposed solution

<Please describe your proposed solution, preferably in the following style:>

```gherkin
Given current checklist status where the repo is missing 1. Description section 2. PR template 3. Repo admins able to accept content reports
When those three items are added
Then community profile checklist will be complete, lowering a bit the barriers for potential contributors
```

**Comment by squeedee** [comment]
PR template #434

**Comment by squeedee** [comment]
Test comment for content reporting.

**Comment by squeedee** [comment]
We don't have team admins, only org admins. I'm hoping content reports reach them effectively? @davidmirror-ops is looking into that.

Otherwise, this is done.

**Comment by martyspiewak** [comment]
@davidmirror-ops is there anything left to do for this issue or can we close it?

**Comment by davidmirror-ops** [comment]
Sorry for the delay, checklist is complete so we can close it.
Thanks!
