### ISSUE TITLE
hack: setup.sh overrides ~/.docker/config.json when setting up cluster

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#206]
### Bug description:

When bringing up a local cluster with `./hack/setup.sh cluster`, `~/.docker/config.json` gets completely overwritten with just the configuration for the local registry.

### Steps to reproduce:

1. have _something_ in ~/.docker/config.json

```bash
printf '{"foo":"bar"}' > ~/.docker/config.json 
```

2. run  the local cluster setup command

```bash
./hack/setup.sh cluster
```

3. notice that we got the previous contents of `~/.docker/config.json` wiped out in favor of the new auth

```bash
cat ~/.docker/config.json | jq '.' -c
```
```console
{"auths":{"10.188.0.3:5000":{"auth":"YWRtaW46YWRtaW4="}}}
```

### Expected behavior:

Rather than having `~/.docker/config.json` overwritten, have the credentials actually going to the intended temporary location as intended by https://github.com/vmware-tanzu/cartographer/pull/175

### Versions:

as of 9e1da8b876db3ba616184ad39310f61161db65f8 (i.e., current `main`)

### Additional context:

I'm almost sure the issue arises from the lack of passing the `DOCKER_CONFIG` variable 

https://github.com/vmware-tanzu/cartographer/blob/9e1da8b876db3ba616184ad39310f61161db65f8/hack/setup.sh#L28

down to the environment of `docker-login.sh`

https://github.com/vmware-tanzu/cartographer/blob/9e1da8b876db3ba616184ad39310f61161db65f8/hack/docker-login.sh#L21

when executing it

https://github.com/vmware-tanzu/cartographer/blob/9e1da8b876db3ba616184ad39310f61161db65f8/hack/setup.sh#L140-L143

to propagate that env down without making it globally exported, we could use the same pattern as in here

https://github.com/vmware-tanzu/cartographer/blob/9e1da8b876db3ba616184ad39310f61161db65f8/hack/setup.sh#L90

where we use `/usr/bin/env` to do so (see [man 1 env](https://man7.org/linux/man-pages/man1/env.1.html))

**Comment by cirocosta** [comment]
cc @idoru (I think you were involved in most of the docker stuff? not sure)

**Comment by idoru** [comment]
Yes your assessment looks correct; We originally `export`ed the `DOCKER_CONFIG` but then went through several iterations (partly shellcheck-motivated) and it looks like we missed this corner case when tidying up.
