### ISSUE TITLE
Rename Pipeline

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#213]
### Description of problem

When we talk about a pipeline object, it's really confusing because it's usually not clear if we're talking about a `carto/Pipeline` or a `tekton/Pipeline`.

### Proposed solution

Literally anything else. `Chronicle`, `ResourceTrigger`, `ImmutableResourceTrigger`, naming is hard so suggestions are welcome.

**Comment by bmoussaud** [comment]
Agree the `Pipeline` is confusing and seems too restrictive to the CI word. To help I'd like to have its definition or aim. The only sentence I found is this single line : https://github.com/vmware-tanzu/cartographer/blob/main/site/content/docs/about.md?plain=1#L29

**Comment by jwntrs** [comment]
@bmoussaud the `SupplyChain` only updates mutable resources. The `Pipeline` resource is a bridge that allows the `SupplyChain` to work with an immutable stream of objects (e.g. `tekton/PipelineRun`). 

The `Pipeline` resource itself will stamp out a new resource (as defined in its `RunTemplate`) every time its params change. It tracks outputs from the stream of objects it produces and exposes the "latest successful run" in its status under the field `latestOutputs`. This way the `SupplyChain` can pick up the result, and propagate the change forward.

**Comment by bmoussaud** [comment]
I haven't seen the `RunTemplate` yet and I haven't found its definition.  From what I read about `Pipeline` and `RunTemplate` in source code and the RFC about `Delivery`,   it seems today `Pipeline` only instantiates a single `RunTemplate` that has no relationship with the concept of `Pipeline`. IMHO a pipeline is a set of tasks. So The execution of the `Pipeline` is to trigger a kind of `kubectl create` of an associate resource via the `RunTemplate` and to maintain its state. Am I right ?

**Comment by jwntrs** [comment]
The `Pipeline` references a single `RunTemplate`, which it uses as a blueprint to create MANY objects. It doesn't really maintain the state of any of its child objects, it just creates them and waits for them to finish.

**Comment by jwntrs** [comment]
@markfisher suggested we call it `Runnable`

**Comment by cirocosta** [comment]
+1 runnable

**Comment by jwntrs** [comment]
@rawlingsj suggested we call it `Sequence`

**Comment by rawlingsj** [comment]
yeah I think there was a general consensus  of `Runnable` and `RunTemplate` in the end
