### ISSUE TITLE
Create securesupplychain fails with message 'image-builder' is waiting to read value '.status.latestImage'

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/cartographer#227]
### Bug description:

trying to create the securesupplychain and the workload is showing an error

### Steps to reproduce:

Following the [example](https://github.com/vmware-tanzu/cartographer/tree/main/examples/source-to-knative-service) in the repo

### Expected behavior:
Secure supply chain should be created with no issues

### Actual behavior:
Workload shows an error

### Logs, k8s object dumps:
Status:
  Conditions:
    Last Transition Time:  2021-10-09T16:56:41Z
    Message:
    Reason:                Ready
    Status:                True
    Type:                  SupplyChainReady
    Last Transition Time:  2021-10-13T10:11:57Z
    Message:               Component 'image-builder' is waiting to read value '.status.latestImage'
    Reason:                MissingValueAtPath
    Status:                Unknown
    Type:                  ComponentsSubmitted
    Last Transition Time:  2021-10-13T10:11:57Z
    Message:               Component 'image-builder' is waiting to read value '.status.latestImage'
    Reason:                MissingValueAtPath
    Status:                Unknown
    Type:                  Ready
  Observed Generation:     1
  Supply Chain Ref:

### Versions:
 - Infrastructure (kind, TKG, GKE etc.: TKG 1.3.1
 - cartographer version: 0.06
 - k8s version: 1.20.3
 - ... other versions of related software being used

**Comment by dineshtripathi30** [comment]
I see that the clusterbuilder is failing with below error.
k describe clusterbuilder go-builder
Name:         go-builder
Namespace:
Labels:       kapp.k14s.io/app=1633798303127913533
              kapp.k14s.io/association=v1.8b935621e2b4e2e0bc63df0adab354b9
Annotations:  kapp.k14s.io/identity: v1;/kpack.io/ClusterBuilder/go-builder;kpack.io/v1alpha1
              kapp.k14s.io/original:
                {"apiVersion":"kpack.io/v1alpha1","kind":"ClusterBuilder","metadata":{"labels":{"kapp.k14s.io/app":"1633798303127913533","kapp.k14s.io/ass...
              kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
API Version:  kpack.io/v1alpha1
Kind:         ClusterBuilder
Metadata:
  Creation Timestamp:  2021-10-18T09:21:00Z
  Generation:          1
  Managed Fields:
    API Version:  kpack.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:observedGeneration:
        f:stack:
    Manager:      controller
    Operation:    Update
    Time:         2021-10-18T09:20:58Z
    API Version:  kpack.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kapp.k14s.io/identity:
          f:kapp.k14s.io/original:
          f:kapp.k14s.io/original-diff-md5:
        f:labels:
          .:
          f:kapp.k14s.io/app:
          f:kapp.k14s.io/association:
      f:spec:
        .:
        f:order:
        f:serviceAccountRef:
          .:
          f:name:
          f:namespace:
        f:stack:
          .:
          f:kind:
          f:name:
        f:store:
          .:
          f:kind:
          f:name:
        f:tag:
    Manager:         kapp
    Operation:       Update
    Time:            2021-10-18T09:21:00Z
  Resource Version:  39025651
  UID:               fe0c52e3-c4f2-44a9-ad70-828e09126b99
Spec:
  Order:
    Group:
      Id:  paketo-buildpacks/go
  Service Account Ref:
    Name:       service-account
    Namespace:  default
  Stack:
    Kind:  ClusterStack
    Name:  stack
  Store:
    Kind:  ClusterStore
    Name:  go-store
  Tag:     projectcartographer/demo-go-builder
Status:
  Conditions:
    Last Transition Time:  2021-10-18T09:21:02Z
    Message:               HEAD https://index.docker.io/v2/projectcartographer/demo-go-builder/blobs/sha256:bf99a8b93828cafcb9c2cdd0028fdfdc3ebc9e8ca878ce893bc945ea584373ec: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)
    Status:                False
    Type:                  Ready
  Observed Generation:     1
  Stack:
Events:  <none>

**Comment by dineshtripathi30** [comment]
since i am using TBS not opensource kpack, can that be a reason here?

**Comment by emmjohnson** [comment]
Looks like we need to update the examples to be clear about the need to configure a docker repository.

**Comment by waciumawanjohi** [comment]
> Looks like we need to update the examples to be clear about the need to configure a docker repository.

This has been done in #489
