### ISSUE TITLE
Running an Informer on a Simple Change

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#23]
We want to use informers to switch to an event driven mechanism for stamped resource updates.

* Use informers to cause a new reconciliation.
* only add informers to GVKs that we are stamping
* run the whole reconcile loop, don't worry about which downstream component depends on the informed component. That's resolved and simplified by "when creating an object, cache any mutations"
* Team agrees that writing a reasonable end to end (perhaps based on the examples) test will help with confidence in such a massive change. May not need to do this for the spike, but worth considering?

Outcome: 
  * To stop putting in a 5 second reconcile

Tasks:
* [x] Remove supply chain dependence on retries
  * [x] delete retries, look for failing tests
  * [x] add tests to integrations that test informers
  * [x] ensure we use a GVK keyed cache to limit adding too many listeners
  * [x] test restart resilience
  * [x] clean up errors vs. status
* [x] do the same for workload
  * [x] delete retries, look for failing tests
  * [x] add tests to integrations that test informers
  * [x] ensure we use a GVK keyed cache to limit adding too many listeners
  * [x] test restart resilience
  * [x] clean up errors vs. status
* [x] do the same for deliverable
  * [x] delete retries, look for failing tests
  * [x] add tests to integrations that test informers
  * [x] ensure we use a GVK keyed cache to limit adding too many listeners
  * [x] test restart resilience
  * [x] clean up errors vs. status
* [x] do the same for delivery
  * [x] delete retries, look for failing tests
  * [x] add tests to integrations that test informers
  * [x] ensure we use a GVK keyed cache to limit adding too many listeners
  * [x] test restart resilience
  * [x] clean up errors vs. status
* [x] add note in contributing to the effect of: 
      > If you have an error condition, set the status of the object. Do not return the error to controller-runtime UNLESS an informer (.Watch) will not trigger a reconcile. If an informer will not cause a reconcile, then return an error so that controller-runtime will retry”
 
Note:
This has already been accomplished by the pipeline service

**Comment by emmjohnson** [comment]
This has not been done anywhere besides pipeline. Opening up now.

**Comment by waciumawanjohi** [comment]
TODO: Delete flaky tests from integration. See here: https://github.com/vmware-tanzu/cartographer/issues/111 and https://github.com/vmware-tanzu/cartographer/pull/195

- [ ] Delete from workload test
- [ ] Delete from deliverable test

**Comment by squeedee** [comment]
Contribution note not done, we might want a better 'how to handle errors' note but I think there's enough convention in place today.
