### ISSUE TITLE
examples: include resource requirements in readme 

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#240]
### Description of problem

by default, Docker for Desktop is configured to run with something like 2 GiB and 2CPU - while that's far far more than enough for Cartographer _alone_, it's certainly pushing the boundaries when installing the other components that we prescribe in the example as we end up with `kpack`, `knative`, `kapp-controller`, `cert-manager` ... it adds up.

### Proposed solution

```gherkin
Given I want to successfully run the example
When I am going through prerequisites
Then I am able to reason about the resources I have available
```

I imagine the best approach here is to have a couple runs of the default setup (per `./hack/setup.sh example`), record mem & cpu usage across some amount of time and then use that as the basis (`*` a multiplier).

**Comment by martyspiewak** [comment]
Might be helpful (maybe sufficient?) to point users at the [ytt overlay](https://github.com/vmware-tanzu/cartographer/blob/main/hack/overlays/remove-resource-requests-from-deployments.yaml) we have for removing resource requirements and explain how to deploy with the overlay if their cluster is running out of resources.

**Comment by cirocosta** [comment]
(from zoom conversation): I think it's useful to keep track of the requirements in the two fronts:

- runtime: w/ a workload submitted, everything running, ballpark: how much gets consumed? knowing that, we can better inform the lower requirements around sizing for, say, docker for mac users that get everything set up w/ the defaults
- reservations: regardless of how much gets actually used, most dependencies set up resource requests which might make folks' installations to fail if their clusters are small. on this front, aside from stating how big those are, we can also point people at the overlay we use in `ci` for stripping those at installation time

**Comment by waciumawanjohi** [comment]
Running the `./hack/setup.sh` examples generally required 380% of CPU and 3.10 GiB of memory.
