### ISSUE TITLE
Logging should follow configured log levels

### ISSUE THREAD

**Issue by idoru** [vmware-tanzu/cartographer#251]
### Description of problem

When deployed, Cartographer logs everything, including messages meant for debugging (e.g. Cache semantic logging).

### Proposed solution

As discussed during community meeting #1 on Oct 20, 2021 we will want to pay closer attention to the log verbosity level, but this requires knowing/having a way to configure Cartographer to use the desired verbosity level in a given installation.

We should have methods employable both in dev and production.

```gherkin
Given logging is configured for a certain V-level
When cartographer runs
Then only errors of that V-level or below are logged
```

## Additional Context

Consider the log level of ALL existing logging statements and categorize using engineering discretion.

## Comments

See also [#284] for development of logging guidelines

**Comment by squeedee** [comment]
finished in #350
