### ISSUE TITLE
Name and Namespace are duplicate in some log lines

### ISSUE THREAD

**Issue by idoru** [vmware-tanzu/cartographer#261]
### Bug description:
Some log lines have duplicate entries for the name and namespace keys.
They appear to be for any of the loggers prefixed with `controller.` e.g.:

```
controller.pipeline-service
controller.supply-chain
controller.workload"
```

### Steps to reproduce:
Deploy and workload and you should see log lines similar to this in the controller's logs:

```
{"level":"info","ts":1634771997.9039302,"logger":"controller.workload","msg":"finished","name":"my-web-app","namespace":"default","name":"my-web-app","namespace":"default"}
```

### Expected behavior:
Name and namespace should only appear once.

### Actual behavior:
Name and namespace are duplicated.

**Comment by squeedee** [comment]
@idoru Is going to review and ratify this story is still true (and also review our contributing guide for logging to see if it clarifies what should happen here)

**Comment by idoru** [comment]
Okay, I've reviewed and this is no longer an issue in the codebase.

I *think* the contributing guide is good in that it refers to the controller runtime advice, which is to log whole objects. Hopefully that's not too subtle, and certainly something we can all be aware of when reviewing.
