### ISSUE TITLE
Templates for delivery and workload are not reusable because of the `owner` reference

### ISSUE THREAD

**Issue by squeedee** [vmware-tanzu/cartographer#268]
### Description of problem

When i write a template, eg a `source-template`
I want to specify the source from either the `workload` or `deliverable`

### Proposed solution

```gherkin
Given A ClusterSourceTemplate that refers to `owner.spec.source.url`
When the resource is stamped (eg `kind:GitRepository`)
Then it works (without me needing to make two templates to match either `owner`)
```

* [ ] Document possible in-ns collisions of templates shared between a SC and Delivery

## Additional Context

* we could just use an alias
* also need to worry about the compound-naming choice if a delivery AND workload live in the same namespace

**Comment by emmjohnson** [comment]
@cirocosta have you noticed this in your work?
