### ISSUE TITLE
Update API links in Carto docs

### ISSUE THREAD

**Issue by DanieldeR** [vmware-tanzu/cartographer#281]
### Bug description:
The links for the API refs in the carto documentation are relative links which are broken.

Reference: The `ref` on https://cartographer.sh/docs/v0.0.6/reference/#clustersourcetemplate is broken

![image](https://user-images.githubusercontent.com/1330996/139466665-94fcda07-0e00-494e-a315-73dcf7d3ae38.png)

**Comment by emmjohnson** [comment]
This has been fixed.

**Comment by squeedee** [comment]
Not fixed on older versions.

**Comment by squeedee** [comment]
Actually not fixed at all. trying a change to see if it works.
