### ISSUE TITLE
Add logging guidelines to CONTRIBUTING.md

### ISSUE THREAD

**Issue by DanieldeR** [vmware-tanzu/cartographer#284]
It should cover @idoru Logging guidelines approach outlined here: https://github.com/vmware-tanzu/cartographer/issues/284#issuecomment-959828568

**Comment by DanieldeR** [comment]
@idoru can you add additional details into this issue to capture all of Cartographer's logging needs?

**Comment by idoru** [comment]
I submit a straw man for pre-IPM:

Scope for this story is to add to CONTRIBUTING a logging guidelines section and to take a timeboxed-pass across each reconciliation loop to apply the agreed upon guidelines. As an outset, I've tried to frame things as broadly as possible:

**Logging Guidelines**

Logging is not a feature and must be taken into consideration with new changes.

Specifically, new code being added should contain an appropriate amount of logging.

When changing code, existing log statements should be altered to make sense.

Reconciliation loops must always log when they start and complete, as well as any errors that occur.

Errors should be logged using `.Error()` 

Initiation and successful completion of non-trivial tasks should be logged using `.Info()`

More verbose logging can be logged using higher log levels `.V(n)`

Logging of any structured content should be done in key-value pairs, e.g. `.Info("task failed", "name", "do-things-task", "params", taskParams)`

If a task has variations in normal behavior, consider logging decision points.


Useful points to consider with writing and reviewing log messages:
- who is this message for?
- what information would be helpful? e.g. relevant parameters, values from config or request context
- what information *should not* be logged?
- what volume of logs will the code be expected to produce? is the V-level appropriate?
- is it coherent with the stream of log messages before or after it?
- is it coherent with the stream of log messages in it’s call trees?
- if code is used in many different call trees or configurations, is it contextualized? (Use FromContext(), WithName() and WithValues())

**Comment by squeedee** [comment]
@emmjohnson I think we can close this, want to look over it together?

**Comment by squeedee** [comment]
This work was done with this PR https://github.com/vmware-tanzu/cartographer/pull/377

closing
