### ISSUE TITLE
Improve installation docs

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/cartographer#292]
### Description of problem

After completing the Cartographer installation process (using kind) and the quick method (single file), some observations arise:

- Black background for code snippets is not specially helpful
- Installation of cert-manager assumes user knows what kapp is, how to install and, especially, why to install that package using kapp
- From this text: 
```
ps.: although we recommend using kapp as provided in the instructions you’ll see here, its use can be replaced by kubectl apply.
```
What's the advantage of using `kapp` if, at the end, users could achieve basically the same using `kubectl apply`?
- A consolidated list of prerequisites is needed
- Some formatting improvements

**Comment by squeedee** [comment]
@davidmirror-ops 
> Black background for code snippets is not specially helpful

Black is common for shell entered commands and their results. We use this as an accepted default.
Light backgrounds are used for code (yaml really) in our docs

Which ones specifically caused you trouble, can you go into detail?

**Comment by squeedee** [comment]
> Installation of cert-manager assumes user knows what kapp is, how to install and, especially, why to install that package using kapp
> From this text:

@emmjohnson  suggests we just point to certmanager's install docs, I concur.

**Comment by squeedee** [comment]
> Some formatting improvements
So much has changed, I can't tell if there are any remaining. @davidmirror-ops do you have any specifics noted?

**Comment by davidmirror-ops** [comment]
> > Some formatting improvements
> > So much has changed, I can't tell if there are any remaining. @davidmirror-ops do you have any specifics noted?

Agreed, so much has changed and so far I would only add:

1. Turn 'Prerequisites; into a numbered list
2. Number the steps on each installation method, just to make it easier for users following the steps

**Comment by davidmirror-ops** [comment]
> @davidmirror-ops
> 
> > Black background for code snippets is not specially helpful
> 
> Black is common for shell entered commands and their results. We use this as an accepted default. Light backgrounds are used for code (yaml really) in our docs
> 
> Which ones specifically caused you trouble, can you go into detail?

I had some previous experience with the [Knative docs ](https://knative.dev/docs/install/serving/install-serving-with-yaml/)where code snippets have a different color schema and somehow it makes it easier (at least for me) to read it.  It's weird as I agree black background is almost universal, but maybe it has to do with the contrast or font size (none of which can be tweaked with Markdown I believe)

**Comment by squeedee** [comment]
> It's weird as I agree black background is almost universal, but maybe it has to do with the contrast or font size (none of which can be tweaked with Markdown I believe)

Yes but they can be tweaked in the CSS. I think the problem of trying to solve how they look comes down to individual preference. However, we could try using lower contrast color schemes, such as Solarized, while maintaining the `shell` vs `code` sensibility. https://en.wikipedia.org/wiki/Solarized

**Comment by squeedee** [comment]
@emmjohnson has done some work on install in #478 so let's move discussion of install into that PR (perhaps you'd like to review the PR @davidmirror-ops?)

Opened #487 for the contrast issue.

Closing, please reopen with comment if something was dropped.
