### ISSUE TITLE
Best match multiple labels on workload

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#298]
### Description of problem

When matching a SupplyChain to a Workload, we currently require that all labels on the supply chain also exist on the workload, but we error if we end up matching more than 1 supply chain.

The labels on a workload should represent characteristics of the workload. When a particular workload gets used across clusters, if a given cluster doesn't have a supply chain matching one of the labels, then the workload should still run.

### Proposed solution

A workload still needs to match all the labels from a supply chain, because if a supply chain runs a "test" step, the workload needs to fulfill the params necessary to run that step. 

However, if we match multiple supply chains, then we should take the supply chain with the most labels. If there is more than one supply chain with the most labels, then we should error.

RFC #319

**Comment by DanieldeR** [comment]
@jwntrs Can an example be added to this issue?

**Comment by jwntrs** [comment]
RFC #319
