### ISSUE TITLE
SupplyChain/Delivery should have serviceAccountName

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#301]
### Description of problem

In certain situations, it may not be desirable to have every workload/deliverable supply its own serviceAccountName.

### Proposed solution

Let Operators configure the serviceAccountName on the SupplyChain/Delivery.

We should prefer a Workload/Deliverable service account over a SupplyChain/Delivery service account if both are provided.

**Comment by jwntrs** [comment]
related to #51

**Comment by emmjohnson** [comment]
This is blocked on #51 correct?

**Comment by martyspiewak** [comment]
If the supply chain provides a service account and we don't find it in the namespace of the workload, should that be a (handled) error or should we fallback to using the default service account? 

the way #345 is implemented it will not fallback to using the default service account if the one provided in the workload cannot be found- would we want the same behavior here?

**Comment by jwntrs** [comment]
> the way #345 is implemented it will not fallback to using the default service account if the one provided in the workload cannot be found- would we want the same behavior here?

I think we want that same behaviour here. The fallback behaviour should only happen if a service account is not provided at various levels.

**Comment by scothis** [comment]
Since `ClusterSupplyChain` cluster scoped and `ServiceAccount` is namespaced, it's ambiguous as to which namespace the `servceAccountName` is referencing. I'm assuming the reference is not to a `ServiceAccount` in the same namespace as the `Workload` since the operator configuring the supply chain would then need to create a the ServiceAccount in every namespace. It could either be enhanced to a `namespace/name`, or a [corev1.SecretReference](https://pkg.go.dev/k8s.io/api/core/v1#SecretReference).

**Comment by martyspiewak** [comment]
I think the assumption we were making was that if the operator was specifying a `serviceAccountName` then they _would_ have to create a service account in the developer namespace, or know that one will exist there.

I would be open to using `namespace/name` instead, though.

When you suggested a secret reference are you suggesting that the operator would reference the secret that holds the token of the service account that has permissions?

**Comment by scothis** [comment]
> When you suggested a secret reference are you suggesting that the operator would reference the secret that holds the token of the service account that has permissions?

Sorry, didn't mean to confuse the case by literally using that type, but something ObjectReference-like that references a ServiceAccount by namespace and name.

**Comment by martyspiewak** [comment]
Gotcha that makes more sense. I think that's reasonable- we shouldn't be using ObjectReference as it says [here](https://pkg.go.dev/k8s.io/api/core/v1#ObjectReference) but, like you said, we can make a similar struct to use.

My one hesitation is that `serviceAccountName` is consistent with the [pod spec](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) and I've struggled to find examples of other resources allowing you to reference a service account in another namespace.

That said, I think specifying service accounts from a cluster scoped resource is a rather unique use-case and so there may be no convention for this. So I think it makes sense to go ahead with this.

@jwntrs do you agree?

**Comment by jwntrs** [comment]
@martyspiewak yeah that makes sense to me. Maybe we be explicit and use something like `serviceAccountRef` to make it extra clear that there's a distinction between the field on a SupplyChain/Delivery and the one on Workload/Deliverable?
