### ISSUE TITLE
No example for ClusterConfigTemplate and broken link

### ISSUE THREAD

**Issue by wiggitywhitney** [vmware-tanzu/cartographer#303]
**On Page:** [link](/docs/v0.0.6/reference/)

**Comment by wiggitywhitney** [comment]
\(^-^)/ Hello!  So nice to meet you, bot friend, and greetings also to the human who reads this eventually.  ♥

**Comment by squeedee** [comment]
@emmjohnson does that mean you've assigned this to yourself?
