### ISSUE TITLE
Release Notes for 0.1.0

### ISSUE THREAD

**Issue by DanieldeR** [vmware-tanzu/cartographer#307]
We need to create human-readable release notes for the 0.0.8 release.

The release notes should follow the linux foundation release notes requirements.

**Comment by squeedee** [comment]
Edit in situ here: https://github.com/vmware-tanzu/cartographer/releases/edit/v0.1.0-rc.1

**Comment by waciumawanjohi** [comment]
Proposed sections for notes:
- Features
- Breaking Changes
- Bug Fixes
- Known Issues

Consider adding a Thanks section to the notes (thank contributors).

**Comment by waciumawanjohi** [comment]
kubectl apply command for installation of this release.
