### ISSUE TITLE
Restructure docs to match style template

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/cartographer#311]
### Description of problem

Cartographer docs use versioning but currently are not following a format where the most recent docs are displayed by default or have a naming convention.

Also is necessary to define the backward support policy and inform that properly on stable and deprecated version docs

### Proposed solution

1. Locate the most recent version docs in a `latest` folder?
2. Check-in new changes to a `main` folder in the docs structure?

### Example

See Velero docs structure as a reference: https://github.com/vmware-tanzu/velero/tree/main/site/content/docs

Also the Velero docs on how to communicate unsupported docs versions: https://velero.io/docs/v1.3.0/

**Comment by emmjohnson** [comment]
This is done.
