### ISSUE TITLE
Missing docs contribution process 

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/cartographer#312]
### Description of problem

Currently, CONTRIBUTING doesn't offer any guidance on how to contribute to Cartographer's documentation

### Proposed solution

Add detailed steps necessary for a potential contributor to check in new content to the project's documentation, including how to handle versioning and how to integrate documentation into the release process

**Comment by davidmirror-ops** [comment]
As a reference, the Contour project makes this process a separate "Contributing to docs" guide:
https://projectcontour.io/resources/contributing-docs/

**Comment by emmjohnson** [comment]
Rash please update this

**Comment by squeedee** [comment]
#377 introduced a CONTRIBUTING guide for logs
