### ISSUE TITLE
clarifications on rfc process

### ISSUE THREAD

**Issue by squeedee** [vmware-tanzu/cartographer#34]
Migrated from Private Gitlab. Original Author Daniel Chen (@chenbh)

- What's the criteria to designate something as an RFC vs regular discussion? What are some examples of a substantial change that should be discussed in an RFC instead of slack/jira/gitlab issues/zoom call?
- What's the process after submitting an RFC? Who's reviewing it and how many reviewers can be expected? 
- What does it mean for an RFC to be merged? Does it signal that the team is comfortable with the idea, but doesn't have any responsibility to actually implement it; or does it turn into an item in the backlog that the team will eventually pick up?
- How does editing merged RFCs work (follow ups, modifications, deprecations)?

I've seen a couple of places where this whole process is documented as `RFC-0000` or `RFC-0001`: [python](https://www.python.org/dev/peps/pep-0001/), [kubernetes](https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/0000-kep-process/README.md), [rust](https://github.com/rust-lang/rfcs/blob/master/text/0002-rfc-process.md)

**Comment by waciumawanjohi** [comment]
I've run into a similar question today. RFC 14 supersedes RFC 3, and I was looking for the proper way to address that. I've decided to adopt the `Status` header from python and kuberenetes (linked above) and mark the RFC as Withdrawn. This preserves the history of that RFC (which would otherwise live forever in a branch, in danger of being deleted).

**Comment by squeedee** [comment]
Comment from #458 

> At community meeting Stephen suggested - every change should be covered by an RFC, but a single RFC could cover multiple change. It is okay to capture uncertainty in RFC and work iteratively - check out CNCF

**Comment by davidmirror-ops** [comment]
From exploring other OSS projects with a RFC process, some observations or common patterns arise:

When to RFC?
1. Adding/removing features
2. Process changes
3.  Breaking changes to the public API

See [react](https://github.com/reactjs/rfcs) and [gRPC](https://github.com/grpc/proposal) as example projects.
