### ISSUE TITLE
Ensure our existing code follows logging best practices

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#347]
### Description of problem

Overall problem outlined here #41

### Proposed solution

Take a time-boxed approach to ensure that all our existing code has the necessary logging in place.

## Additional Context

We should be following the ideals that @idoru outlined for logging here: https://github.com/vmware-tanzu/cartographer/issues/284#issuecomment-959828568

**Comment by squeedee** [comment]
Finished in https://github.com/vmware-tanzu/cartographer/pull/377

closing
