### ISSUE TITLE
No Contexts on structs

### ISSUE THREAD

**Issue by squeedee** [vmware-tanzu/cartographer#361]
We should address Ciro's concerns wrt
* No contexts stored in constructs, even in main
* Proper Sig handling in main to cancel all requests.

trying to follow the chain of `ctx` being propagated through the code, one thing that I noticed that seems a little off is how we pass from `cmd/main.go` down to `pkg/root`:

- here we're passing it via a struct field

https://github.com/vmware-tanzu/cartographer/blob/1bd6074009be49c21f238aa96d54537912a2669e/cmd/cartographer/main.go#L54

- here we're consuming from the struct

https://github.com/vmware-tanzu/cartographer/blob/1bd6074009be49c21f238aa96d54537912a2669e/pkg/root/root.go#L112-L113

that's not very usual, and discouraged - the idiomatic way of doing doing would be to pass it via the function instead, being the first argument of the list.

it's not something introduced in this PR, but, sounds somewhat appropriate to patch given the context (no pun intended) 😁  wdyt?

thx!

_Originally posted by @cirocosta in https://github.com/vmware-tanzu/cartographer/issues/360#issuecomment-973157506_

**Comment by squeedee** [comment]
@cirocosta there was a bullet point in this story to include the proper signal handling. I'm happy to write another story or reopen this one, unless there's a reason you did not include signal handling in your PR?

**Comment by cirocosta** [comment]
hey @squeedee , no worries about that - it's been done in #372 already 👍
