### ISSUE TITLE
readme: update warning to account for new use of serviceaccounts

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#393]
### Description of problem

with the introduction of #345, we know have a very different security profile compared to before, so, we should reflect this _new world_ in the readme too.

### Proposed solution

```gherkin
Given that I am looking at the README
When I try t figure out what the controller can do
Then I can easily tell that it can has read-only view for all of the k8s api, but not write permissions
```

**Comment by martyspiewak** [comment]
This warning section was removed entirely in #453. Is it necessary to document the exact permissions the controller has in the README now that the permissions are more reasonable?

Perhaps there is a better place we can document this?

**Comment by cirocosta** [comment]
> _Perhaps there is a better place we can document this?_

👍 👍  

#435
