### ISSUE TITLE
Add a troubleshooting section to the docs

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#395]
### Description of problem

We don't have a troubleshooting guide in our docs.

### Proposed solution

Cover some of the most common error cases that people can expect to encounter.

- [x] Very top of the page should say check your workload status.
- [x] MissingValueAtPath
- [ ] SupplyChainNotFound
- [ ] Why nothing gets triggered when changing underlying objects that we aren't watching (tekton/Pipeline)
- [ ] Workload/Delivery status says all good, but the last ClusterTemplate is actually failing.
- [ ] ???

**Comment by squeedee** [comment]
https://vmware.slack.com/archives/C0186SB6ATY/p1638396569345200
