### ISSUE TITLE
Add an architecture section to the docs

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#396]
### Description of problem

We have some really great architecture diagrams kicking around, let's add a section to the docs that includes them.

### Proposed solution

Lets create a doc that covers the following:

- [x] Component interactions
- ~[ ] Permissions model~ moved to #435
- [x] object hierarchy in workload namespace

**Comment by DanieldeR** [comment]
Ultimately the scope of this issue is to take all of the architectures diagrams that have been previously created and make them available publicly.

Additionally, the source of the diagrams should be available publicly.

**Comment by squeedee** [comment]
Permissions model not done, new story #435
