### ISSUE TITLE
Controller logs have timestamps in an unreadable format

### ISSUE THREAD

**Issue by hectorj2f** [vmware-tanzu/cartographer#397]
### Bug description:
Please provide a clear and concise description of what the bug is.
Controller logs have timestamps in an unreadable format.

```
{"level":"info","ts":1637864479.7085538,"logger":"controller.deliverable","msg":"deliverable no longer exists","name":"workload","namespace":"ootb-supply-chain-basic-inner","deliverable":"ootb-supply-chain-basic-inner/workload"}
{"level":"info","ts":1637864479.708634,"logger":"controller.deliverable","msg":"finished","name":"workload","namespace":"ootb-supply-chain-basic-inner"}
{"level":"info","ts":1637864479.7611723,"logger":"controller.deliverable","msg":"started","name":"workload","namespace":"ootb-supply-chain-testing-inner"}
{"level":"info","ts":1637864479.761236,"logger":"controller.deliverable","msg":"deliverable no longer exists","name":"workload","namespace":"ootb-supply-chain-testing-inner","deliverable":"ootb-supply-chain-testing-inner/workload"}
{"level":"info","ts":1637864479.76127,"logger":"controller.deliverable","msg":"finished","name":"workload","namespace":"ootb-supply-chain-testing-inner"}
{"level":"info","ts":1637864479.9576738,"logger":"controller.deliverable","msg":"started","name":"workload","namespace":"ootb-supply-chain-testing-outer"}
{"level":"info","ts":1637864479.9577823,"logger":"controller.deliverable","msg":"deliverable no longer exists","name":"workload","namespace":"ootb-supply-chain-testing-ou^C{"level":"info","ts":1637864479.9578032,"logger":"controller.deliverable","msg":"finished","name":"workload","namespace":"ootb-supply-chain-testing-outer"}
{"level":"info","ts":1637864480.1621509,"logger":"controller.deliverable","msg":"started","name":"workload","namespace":"ootb-supply-chain-basic-inner"}
{"level":"info","ts":1637864480.1622038,"logger":"controller.deliverable","msg":"deliverable no longer exists","name":"workload","namespace":"ootb-supply-chain-basic-inner","deliverable":"ootb-supply-chain-basic-inner/workload"}
{"level":"info","ts":1637864480.1622267,"logger":"controller.deliverable","msg":"finished","name":"workload","namespace":"ootb-supply-chain-basic-inner"}
{"level":"info","ts":1637864480.2109632,"logger":"controller.deliverable","msg":"started","name":"workload","namespace":"ootb-supply-chain-testing-inner"}
{"level":"info","ts":1637864480.2110088,"logger":"controller.deliverable","msg":"deliverable no longer exists","name":"workload","namespace":"ootb-supply-chain-testing-inner","deliverable":"ootb-supply-chain-testing-inner/workload"}
```

### Expected behavior:
Please provide a clear and concise description of what you expected to happen.

I'd expect cartographer to follow certain Kubernetes recommendation in terms of logging form such as https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md#logging-header-formats.

### Versions:
 - cartographer version v0.0.8-rc.4

**Comment by cirocosta** [comment]
hey @hectorj2f,

thanks for sharing the doc, I'm a bit surprised there's no mention of timezone in there / a recommendation based on an RFC 🤔  I imagine we'd go with +0 by default?

out of curiosity, is the timestamp encoder something that folks usually make configurable?

currently we use the defaults from controller-runtime (see [TimeEncoder](https://github.com/kubernetes-sigs/controller-runtime/blob/4d10a0615b11507451ecb58bfd59f0f6ef313a29/pkg/log/zap/zap.go#L170-L172)), i.e., [EpochTimeEncoder](https://github.com/uber-go/zap/blob/eaeb0fc72fd23af7969c9a9f39e51b66827507ca/zapcore/encoder.go#L95-L100):

```go
// EpochTimeEncoder serializes a time.Time to a floating-point number of seconds
// since the Unix epoch.
func EpochTimeEncoder(t time.Time, enc PrimitiveArrayEncoder) {
	nanos := t.UnixNano()
	sec := float64(nanos) / float64(time.Second)
	enc.AppendFloat64(sec)
}
```

so I'm wondering if that's something that folks are already used to (and thus, probably configured whatever tools folks use to parse structured logging to consume such format). 

thank you!

**Comment by hectorj2f** [comment]
@cirocosta I have not seen the timestamp encoder as anything to make configurable for a k8s based operator. 
We're also using `sigs.k8s.io/controller-runtime` Log:
```
2021-11-30T03:56:39.228Z        DEBUG   controller-runtime.manager.controller.image Reconcile       {"reconciler group": "starting", "reconciler kind": "Image", "name": "workload", "namespace": "ootb-inner"}


```

**Comment by cirocosta** [comment]
ooh, I see - those can be activated with the `-dev` flag for `cartographer` (so that it toggles "human readable logs", i.e., makes use of zaps' "devmode"):

https://github.com/vmware-tanzu/cartographer/blob/9288632e2e9772a25dedaa5e9d9b8886849b9ccf/cmd/cartographer/main.go#L50 

that then under the hood switches the production-level setup (i.e., the json-encoded logs as we default to) to "consoleencoding":

```go
// NewDevelopmentEncoderConfig returns an opinionated EncoderConfig for
// development environments.
func NewDevelopmentEncoderConfig() zapcore.EncoderConfig {
	return zapcore.EncoderConfig{
		// Keys can be anything except the empty string.
		TimeKey:        "T",
		LevelKey:       "L",
		NameKey:        "N",
		CallerKey:      "C",
		FunctionKey:    zapcore.OmitKey,
		MessageKey:     "M",
		StacktraceKey:  "S",
		LineEnding:     zapcore.DefaultLineEnding,
		EncodeLevel:    zapcore.CapitalLevelEncoder,
		EncodeTime:     zapcore.ISO8601TimeEncoder,
		EncodeDuration: zapcore.StringDurationEncoder,
		EncodeCaller:   zapcore.ShortCallerEncoder,
	}
}

// NewDevelopmentConfig is a reasonable development logging configuration.
// Logging is enabled at DebugLevel and above.
//
// It enables development mode (which makes DPanicLevel logs panic), uses a
// console encoder, writes to standard error, and disables sampling.
// Stacktraces are automatically included on logs of WarnLevel and above.
func NewDevelopmentConfig() Config {
	return Config{
		Level:            NewAtomicLevelAt(DebugLevel),
		Development:      true,
		Encoding:         "console",
		EncoderConfig:    NewDevelopmentEncoderConfig(),
		OutputPaths:      []string{"stderr"},
		ErrorOutputPaths: []string{"stderr"},
	}
}
```

https://github.com/uber-go/zap/blob/eaeb0fc72fd23af7969c9a9f39e51b66827507ca/config.go#L135-L170

so, just to make sure I understand: are you suggesting that we should default to the behavior of `-dev` as that's more common, or is the ask here specifically about just the timestamp (which could be either the same as used for console encoding - `zapcore.ISO8601TimeEncoder`)?

**Comment by hectorj2f** [comment]
@cirocosta The main purpose is to help troubleshooting issues, having a human readable timestamp would be helpful in my opinion.

**Comment by jwntrs** [comment]
> ooh, I see - those can be activated with the -dev flag for cartographer (so that it toggles "human readable logs", i.e., makes use of zaps' "devmode")

Closing since this is solved by @cirocosta suggestion of using the `-dev` flag

**Comment by hectorj2f** [comment]
@jwntrs In a production cluster, we'll suggest to enable the flag `-dev` to troubleshoot problems. I just want to be sure of that.

**Comment by jwntrs** [comment]
> @jwntrs In a production cluster, we'll suggest to enable the flag -dev to troubleshoot problems. I just want to be sure of that.

@hectorj2f you do have a point.

`zap` and `klog` definitely have different opinions on defaults. I'll re-open so we can revisit whether we should move to klog or just adapt to some of their recommendations.

**Comment by emmjohnson** [comment]
@squeedee can you provide an update

**Comment by scothis** [comment]
[Structured logs](https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/) are optimized for machine readability over human readability. Their main advantage is that it's easy to attach additional key-value metadata to log entries that make filtering and correlation much easier.

 It's expected that operators in a production environment will be looking at logs with a dedicated tool rather than viewing the raw stdout. The dev flag mentioned above flips that optimization to be focused on human readability.

**Comment by squeedee** [comment]
Yes there's no reason to swap log tools for the sake of 'human readable timestamps'. Both klog and zap use decimal epoch timestamps in their default json structured logging. 

@hectorj2f I don't see the point in offfering -dev (although it is an option and can remain one) as a solution. You have to restart the controller and re-establish the original issue you had. I propose that if this is important enough for you, that we find/develop a tool that simplifies reordering, filtering and searching structured machine readable logs.
