### ISSUE TITLE
Update Examples

### ISSUE THREAD

**Issue by DanieldeR** [vmware-tanzu/cartographer#402]
Cartographer only has a single example at the moment. Instead, we should have cumulatively more complex examples which will allow:
* New users a starting place to grab concepts; and
* more advanced users a place to see complex supply chains

In order to achieve this, the following updates to the examples should be made:

- [x] Remove (repurpose) the current source to Knative example
- [x] Add an examples overview page that details - at a hight level - each of the examples and what their purpose is
- [x] Create a simple example (source + kpack + knative)
- [x] Create a slightly more complex example building on the concepts of the first supply chain (source + tekton + kpack + knative) - similar to our current source to knative example

The more complex example (#405) will be handled separately.

**Comment by DanieldeR** [comment]
For the time being, we should be ensuring that each of these examples are working as expected via testing.

**Comment by waciumawanjohi** [comment]
See #240 
Consider adding info about necessary cluster size

**Comment by waciumawanjohi** [comment]
Change the default registry name in `values.yaml` so that it's more obvious to users that have inadvertantly used the default. e.g. projectcartographer => a-great-registry-to-which-i-have-access
See #227

**Comment by emmjohnson** [comment]
See #382 
Consider choosing a more descriptive name for the service account
