### ISSUE TITLE
Complex Example

### ISSUE THREAD

**Issue by DanieldeR** [vmware-tanzu/cartographer#405]
Create a complex example which details using multiple environments (source + tekton + kpack + cluster config + delivery + knative)

**Comment by davidmirror-ops** [comment]
Should this example include scanning?
In previous conversations with members from the CNCF Security TAG, they brought up the SLSA framework which basically comprises source --> build --> package --> use with security requirements common to all systems involved in the supply chain:
https://slsa.dev/requirements#what-is-slsa

**Comment by DanieldeR** [comment]
@davidmirror-ops maybe, there are pieces that make scanning in a supply chain easier, particularly with Grype for example, but they are not quite open source just yet. I suggest that we keep the issue as is for now and see what happens with those additional components.

**Comment by cirocosta** [comment]
@DanieldeR I think we can still work on something here with a combination of
Runnable, Tekton, and Trivy.

given that with [trivy] we're able to scan both container images and source
code in a filesystem, we could start with a stage in the supplychain chain
where we run `trivy fs .` on the source code we gather from `GitRepository`


```

source-provider <-[src]- src-validations     <-[src]-    image-building   <-[img]- img-validations
       .                       .                                .                       .
   GitRepository            Runnable                      kpack/Image               Runnable
                               .                                                        .
                       tekton/PipelineRun                                          tekton/TaskRun
                           tasks:                                                    name: scan-image
                             - - name: extract code
                             - - name: test
                               - name: scan
```

one could make the example even better (at the price of complexity) by                                                  automatically triggering new scans whenever a new vulnerability database is                                             published by introducing some form of ImageRepository that keeps track of base
images that contain such vulnerability database (although yeah, just for an
example, might be too far off).

---

to @davidmirror-ops 's point around `slsa` though, naturally there'd be be
more work to be put to get closer to adhering fully to the guidances in there,
but something like that supplychain I mentioned could be a step to get there


[trivy]: https://github.com/aquasecurity/trivy

**Comment by squeedee** [comment]
Team want's to have a chat with the VMWare TCE team to see what they're already planning to ship. It could be a great source of both living examples, and a solution that Cartographer New User's can trial to get up to speed quickly.

**Comment by squeedee** [comment]
Look at #402 and see if that's the same as this story.

**Comment by squeedee** [comment]
> details using multiple environments
@DanieldeR 

Does multiple environments imply inner/outer loops, or multi cluster?

**Comment by DanieldeR** [comment]
The intention is multiple cluster. Demonstrating the path to production of a customer that may have multiple clusters for environments i.e. dev to staging. It should theoretically be similar to the previous example with gitea.
