### ISSUE TITLE
Missing links in README

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/cartographer#408]
### Bug description:
The following links are broken in the README:

1. About Cartographer: https://github.com/vmware-tanzu/cartographer/blob/main/site/content/docs/about.md
2. Spec Reference: https://github.com/vmware-tanzu/cartographer/blob/main/site/content/docs/reference.md 
3. Installation: https://cartographer.sh/docs/install
4. Uninstall http://cartographer.sh/docs/uninstall

If this was produced by #351, should we consider pinning the most recent version to `latest` to avoid having to update links in the README with each new release?

**Comment by squeedee** [comment]
None of these links to docs content should point to the repository, they should point to the doc site.
Yes, doc site links should use latest, eg: https://cartographer.sh/docs/latest/install/ 

Further, we should have a link checker run over our top level `/*.md` files on github to ensure they link correctly, and one for https://cartographer.sh
