### ISSUE TITLE
Upgrade testing

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#417]
### Description of problem

We want to guarantee an upgrade path for users.

### Proposed solution

Add a workflow that deploys the previous release, and tests an upgrade to the current candidate.

**Comment by martyspiewak** [comment]
A couple of questions on this:

1. Do we test an upgrade from the last release of any kind (including pre-releases, etc.), or only from the latest final release?
   * I would think the answer should be the latest final release.
2. Do we run this test as part of the validation workflow that runs on every commit, or only in the release workflow?
   * It feels like a bit much to run on every commit, but it also doesn't seem great to only learn about an upgrade failure when we're ready to release.
3. What do we want to exist in the cluster at upgrade time? One of everything (i.e. a workload, runnable, deliverable, etc.)? Is it sufficient to test with less than that? Or do we maybe need more than one of each?

**Comment by emmjohnson** [comment]
We should be testing 0.1.0 and 0.1.+. It doesn't make sense to add a test now. What two releases are we testing?

**Comment by squeedee** [comment]
> It feels like a bit much to run on every commit,
Perhaps ensuring we have a manual trigger?

**Comment by squeedee** [comment]
## Pre-IPM notes:

>Do we test an upgrade from the last release of any kind (including pre-releases, etc.), or only from the latest final release?

Latest full release (non-alpha/beta) to current PR and Mainline

> Do we run this test as part of the validation workflow that runs on every commit, or only in the release workflow?

As above, all the time. Let's work out how to make it not awful? - We do have force merge for expediency, at least in the core team.

> What do we want to exist in the cluster at upgrade time? One of everything (i.e. a workload, runnable, deliverable, etc.)?

Start with a gitops style example or all examples (as per e2e today)
1. Install n-1
2. install gitops example (already tested in current validation)
3. upgrade to n
4. push a new commit to trigger gitops supply chain (and test it resolves)
