### ISSUE TITLE
Show more complete information under `kubectl explain` for Templates

### ISSUE THREAD

**Issue by ciberkleid** [vmware-tanzu/cartographer#420]
### Description of problem

I am finding that using `kubectl explain` is incredibly helpful in understanding and composing templates and supply chains. However, the information yielded by `kubectl explain` seems incomplete, making it difficult to grasp how to configure or troubleshoot certain things.

For example, in ClusterSourceTemplate, the urlPath and revisionPath tell the template where to get the values it will map to some output fields but `kubectl explain clustersourcetemplate…` does not show the output fields.

### Proposed solution

```gherkin
Given there are fields in a spec
When a user explores the spec using `kubectl explain`
Then all fields appear in the output
```

**Comment by squeedee** [comment]
One frustration I've discovered is that `explain` just smashes the whole description together.

Below is k8s own podspec showing a table, but explain smooshing it to pieces

![Screen Shot 2022-01-18 at 11 34 38 AM](https://user-images.githubusercontent.com/27838/149979444-24cd7f5b-a4d7-4f59-80d2-97626195253e.png)
