### ISSUE TITLE
Integration Tests for Informers

### ISSUE THREAD

**Issue by waciumawanjohi** [vmware-tanzu/cartographer#428]
### Description of problem

There are a number of informers registered in the registrar:
- https://github.com/vmware-tanzu/cartographer/blob/475b58edab81720e27a628c19c4700eea5c1dec4/pkg/registrar/registrar.go#L128-L135
- https://github.com/vmware-tanzu/cartographer/blob/475b58edab81720e27a628c19c4700eea5c1dec4/pkg/registrar/registrar.go#L270-L277

Integration coverage of these is sparse. There should be enough coverage to give us confidence that there is no regression.

**Comment by scothis** [comment]
Assuming #444 is implemented, I'd tend to skip integration tests for informers as there's not much (any?) business logic. Instead focus on e2e tests for all of cartographer in a real cluster.

**Comment by emmjohnson** [comment]
Closing per Scott's comment
