### ISSUE TITLE
Remove controller logic from informers

### ISSUE THREAD

**Issue by martyspiewak** [vmware-tanzu/cartographer#444]
### Description of problem

In order to determine which workloads/deliverables to re-reconcile on changes, our informers perform the same work that our controllers do to find the [best matching supply chain/delivery](https://github.com/vmware-tanzu/cartographer/blob/e875402c1f38c2aa45dafc07bad18fdf00f24998/pkg/registrar/map_functions.go#L160-L168) and [which service account is being used for a workload](https://github.com/vmware-tanzu/cartographer/blob/e875402c1f38c2aa45dafc07bad18fdf00f24998/pkg/registrar/map_functions.go#L402-L403). This id not ideal as this logic should be isolated to the controller.

### Proposed solution

We can make use of the [Knative tracker](https://github.com/knative/pkg/tree/main/tracker) so that the controller can maintain sole responsibility for determining which resources should trigger a reconciliation for a workload/deliverable, and the informers can ignore most Cartographer-specific logic.

### Example

There are other projects which have adapted this type of tracking based off the Knative tracker:
* Reconciler-runtime: see [readme](https://github.com/vmware-labs/reconciler-runtime#tracker), [tracker.go](https://github.com/vmware-labs/reconciler-runtime/blob/main/tracker/tracker.go) 
* Kpack: see [tracker.go](https://github.com/pivotal/kpack/blob/main/pkg/tracker/tracker.go)

## Additional Context

cc @scothis

**Comment by scothis** [comment]
Notice the copyright header on both tracker.go files 🤣 

The other half of the tracker is a function that bridges back to the informer/workqueue https://pkg.go.dev/github.com/vmware-labs/reconciler-runtime/reconcilers#EnqueueTracked

**Comment by martyspiewak** [comment]
Some thoughts when spiking on this:

what if:
1. the workload controller tracks supply chain A for workload X 
2. supply chain B is applied and is a better match for workload X

How will workload X get enqueued? 

(Also, if workload X is enqueued for some other reason and starts to track supply chain B, we need to verify that the tracking for supply chain A is removed)

**Comment by squeedee** [comment]
I feel like the baseline is to be referentially transparent. The question becomes wether a supply chain is just a "function" or is itself state, and I would err on the side of state. The pure function is our controller, the state applied is Workload/supplychains. 

Given Workload a, Supply Chains A and B, where B matches a better
then, reconcile(a,[A,B]) => stamp B of a (always, no matter if the state was (a,[A]) beforehand )

We behave the same way if the workload changes, ```reconcile(a,[A])  == reconcile(a`,[A])```

**Comment by squeedee** [comment]
Would it hurt if, when a supply chain is applied, all system workloads are enqueued? Put's us in a situation no worse than controller-restart? It's a trigger to tell all workloads they need to use their own logic to decide what happens, and it's a fair one considering the high likelyhood that a new (or modified) supply chain would have broad knock on affects to the workloads on the cluster

**Comment by martyspiewak** [comment]
I was thinking the same thing. The only thing is we would have to re-reconcile all workloads not only when a new supply chain is applied, but also when any supply chain labels are modified, because that could affect which workloads match best.

That gets a little trickier because we'd need a way to see what changed in the supply chain and I'm not so sure how we'd do that elegantly. (One half-baked thought I had was that we could store the last config of the supply chain in it's status so that when a change comes in we could compare the spec to the status...but I haven't really thought that through well enough yet.)
