### ISSUE TITLE
Publish a ROADMAP 

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/cartographer#471]
### Description of problem

Currently, the project repository lacks a ROADMAP document that could guide users and potential contributors about the future of the project and align ideas and contributions around a clear vision.

**Comment by squeedee** [comment]
Ask for Zach Robinson to provide us with the details for this (or edit the docs directly)

**Comment by davidmirror-ops** [comment]
> Ask for Zach Robinson to provide us with the details for this (or edit the docs directly)

Correct, Zach is already aware of this request and will provide updates when available

**Comment by emmjohnson** [comment]
Example from paketo - https://github.com/paketo-buildpacks/community/blob/main/ROADMAP.md

**Comment by davidmirror-ops** [comment]
Several examples discussed recently:

1. Tanzu Community Edition (interesting as it also uses proposals/RFCs): https://github.com/vmware-tanzu/community-edition/blob/main/ROADMAP.md
2. Velero: https://github.com/vmware-tanzu/velero/blob/main/ROADMAP.md
3. Paketo Buildpacks process starts with an open discussion where users upvote: https://github.com/paketo-buildpacks/feedback/discussions/24
