### ISSUE TITLE
Managing supply chains

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#541]
### Description of problem

As a supply chain author I would like managing multiple supply chains to be simpler.

Currently supply chains are a static graph of resources. This means that if some of my apps need to build an image from source, and others need to use a pre-built image, there is no easy way to do this within a single supply chain. Managing multiple supply chains gets especially hard when the rest of the graph looks the same for both these applications, so maintaining two separate supply chains means constantly keeping them in sync.

### Possible solutions
Conditional branching in supply chains [RFC9](https://github.com/vmware-tanzu/cartographer/pull/75)
Composable supply chains [RFC5](https://github.com/vmware-tanzu/cartographer/pull/72)
Conditional branching from inputs  [RFCXX](https://github.com/vmware-tanzu/cartographer/pull/570)

**Comment by cirocosta** [comment]
closing as we can make use of the native github epics view https://github.com/orgs/vmware-tanzu/projects/40/views/3
