### ISSUE TITLE
Document a multi-cluster setup

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#543]
### Description of problem

We currently have some good examples of a [supply chain](https://github.com/vmware-tanzu/cartographer/blob/main/examples/gitwriter-sc/README.md) and a [delivery](https://github.com/vmware-tanzu/cartographer/blob/main/examples/basic-delivery/README.md
) that show how you would support gitops across multiple clusters. We also have a [really good diagram](https://cartographer.sh/docs/v0.1.0/architecture/#complete-supply-chain-and-delivery-with-gitops
) that shows what a multi-cluster setup looks like. It would be nice if we had a landing page in our docs that aggregates all this information so when people ask about multi-cluster support we can point them to a single place.

**Comment by jwntrs** [comment]
@zrob do you want this multi cluster setup to be documented separate our do you want to roll this into our tutorials?

**Comment by zrob** [comment]
This should be separate from our tutorials. 

Aspects that we need to capture.

- What is installed where
- Describe how to setup a git checkin in between
- How to create a Deliverable 
- A minimal promotion flow.  build -> staging -> prod
  - this should be based on a gitops flow using PRs to promote b/t the above environments
  - the supply chain will be committing to one branch. a human would create a PR to merge into another branch to trigger the promotion  

 

Add a top-level section `Outcomes` with a new item called `Multi-cluster Promotion` that has the content from this story.
