### ISSUE TITLE
Submit cartographer to TCE

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#578]
[Submitted proposal](https://github.com/vmware-tanzu/community-edition/issues/3024) to TCE to have Cartographer included.
When it's accepted (it's very close, we just need to agree to contributor agreement) then [we need to do the work](https://github.com/vmware-tanzu/community-edition/tree/main/docs/packaging) to include it in their packaging. 

# Options:
1. Use our current impgpkg/kappctrl packages  and ensure they are in a repository that can be used by TCE
2. remove the current packaging and create a repository that's just like everyone else's in the TCE ecosystem to produce and ship the packages.

**Comment by squeedee** [comment]
@cirocosta says there needs to be a specific container repository - we probably need a process to move our exisiting packages?

**Comment by cirocosta** [comment]
@squeedee yeah that's one of the approaches that some teams like `kpack` have been taking: https://github.com/vmware-tanzu/package-for-kpack (see PR that added `kpack` to TCE: https://github.com/vmware-tanzu/community-edition/pull/2878

ultimately what's important is to have a way of providing a Package object to the TCE repository (which fetches it making use of `vendir`, so, more like "tce pulls it from you"), with the bundle referenced by the Package being served by the VMware container image registry (this last item is probably the reason why it'd be important for us to have a separate repository - like, `package-for-cartographer` - as our bundle is in DockerHub)

**Comment by cirocosta** [comment]
- [vmware-tanzu/package-for-cartographer](https://github.com/vmware-tanzu/package-for-cartographer) (soon to be public)
- https://github.com/vmware-tanzu/community-edition/pull/3262
