### ISSUE TITLE
[Feature Request] Add short names for CRDs

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/cartographer#600]
### Description of problem

The names of CRDs in cartographer are quite long and typing them out constantly can be tedious.

### Proposed solution

Add Short names to the CRDs of cartographer to allow for quick access to crds via easy to understand short names

### Example

Clustersupplychain -> csc
Clustertemplate -> ct
Clusterimagetemplate -> cit
Clusterconfigtemplate -> cct
Clustersourcetemplate -> cst
Clusterdeploymenttemplate -> cdt
Clusterruntemplate -> crt
clusterdelivery -> cd
runnable -> run
Workload -> wld
Delivery -> dlv

## Additional Context

The shorter names such as workload,runnable and deliverable are less important to have these but for the templates and supply chain it would enhance the UX greatly.

**Comment by squeedee** [comment]
I love this idea. I feel we should check for collisions with popular or in-platform crd's and then proceed

**Comment by vrabbi** [comment]
to get the list of existing shortnames in a cluster, it is not a simple kubectl command as they dont support json output for the api-resources command but ive built i simple command with sed to do the same and ran this against a TAP cluster running on EKS so it has all the platform CRDs as well as some additional ones from EKS:

the command is:
kubectl api-resources --sort-by=name | awk '{print $1 "  " $2}' | sed '/\//d' -

on a TAP 1.0 on EKS with the Full profile installed the list is:

NAME  SHORTNAMES
accelerators  acc
apiexportrolebindings  aerb
apiresourceimports  ari
bindings  v1
builders  bldr,bldrs
builds  cnbbuild,cnbbuilds,bld,blds
certificaterequests  cr,crs
certificates  cert,certs
certificates  kcert
certificatesigningrequests  csr
channels  ch
clusterapigroupimports  agi
clusterbuilders  clstbldr,clstbldrs
clusterdomainclaims  cdc
clusterresourceexportmonitors  emon
clusterresourceimportmonitors  imon
componentstatuses  cs
compositecontrollers  cc,cctl
configmaps  cm
configurations  config,cfg
cronjobs  cj
customresourcedefinitions  crd,crds
daemonsets  ds
decoratorcontrollers  dec,decorators
deployments  deploy
domainmappings  dm
endpoints  ep
events  ev
events  ev
extensionservices  extensionservice,extensionservices
gitrepositories  gitrepo
helmcharts  hc
helmrepositories  helmrepo
horizontalpodautoscalers  hpa
httpproxies  proxy,proxies
images  img
images  cnbimage,cnbimages,img,imgs
ingresses  ing
ingresses  ing
ingresses  kingress,king
inmemorychannels  imc
limitranges  limits
namespaces  ns
networkpolicies  netpol
nodes  no
packageinstalls  pkgi
packagemetadatas  pkgm
packagerepositories  pkgr
packages  pkg
persistentvolumeclaims  pvc
persistentvolumes  pv
pipelineruns  pr,prs
podautoscalers  kpa,pa
poddisruptionbudgets  pdb
pods  po
podsecuritypolicies  psp
podtemplates  v1
priorityclasses  pc
replicasets  rs
replicationcontrollers  rc
resourceclaimpolicies  policies
resourceclaims  claims
resourcequotas  quota
revisions  rev
routes  rt
secretexports  se
secretimports  si
secrets  v1
securitygrouppolicies  sgp
serverlessservices  sks
serviceaccounts  sa
services  svc
services  kservice,ksvc
statefulsets  sts
storageclasses  sc
subscriptions  sub
tanzunetdependencyupdaters  dependencyupdater,dependencyupdaters
taskruns  tr,trs
tlscertificatedelegations  tlscerts
vspherebindings  vsb
vspheresources  vss



it does not seem to have any overlapping shortnames with platform CRDs nor have i come accross such short names but they may exist out in the wild.
