### ISSUE TITLE
Run tests with debug logging. Also fix this failure

### ISSUE THREAD

**Issue by squeedee** [vmware-tanzu/cartographer#615]
## Bug

This line https://github.com/vmware-tanzu/cartographer/blob/29fcadaa57dc7deb25a878abc4a4ff707374bf12/pkg/realizer/runnable/realizer.go#L137
crashes with debug logging. 

Repro: https://github.com/vmware-tanzu/cartographer/pull/616

## Expected Behaviour 

We should ensure that all logging is tested in kuttl, e2e and integrations, and does not crash the controller.

**Comment by zrob** [comment]
Open an upstream bug. The kuberenetes-helper tries to read empty unstructured.unstructured it goes boom

**Comment by emmjohnson** [comment]
https://github.com/kubernetes-sigs/controller-runtime/blob/master/TMP-LOGGING.md#logging-kubernetes-objects

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/log/zap/kube_helpers.go

**Comment by emmjohnson** [comment]
Upsteam - https://github.com/kubernetes-sigs/controller-runtime/pull/1807
