### ISSUE TITLE
Package/PackageInstall resources in release use `0.0.0-dev` version

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/cartographer#622]
### Bug description:

The `Package` and `PackageInstall` resources included in the 0.2.2 release both use `0.0.0-dev` as the Cartographer version. Since these versions are for a release, I'd expect them to include the release's version number.

### Steps to reproduce:

Please provide a set of steps to reproduce the behavior (example):
1. Download https://github.com/vmware-tanzu/cartographer/releases/download/v0.2.2/package.yaml or https://github.com/vmware-tanzu/cartographer/releases/download/v0.2.2/package-install.yaml
2. Observe the Cartographer version number is defined as `0.0.0-dev`

### Expected behavior:

The Package resources should include the version number of the release.

### Actual behavior:

By using the same version number for multiple Package resources, this will update the existing Package when applied to the cluster. This breaks kapp-controller's version selector and its ability to selectively rollout new versions.

### Versions:

 - cartographer version v0.2.2

**Comment by cirocosta** [comment]
yeah indeed, good catch - with the new approach of releasing by promoting the Draft release that gets created on every commit that lands in `main`, we end up always having that `0.0.0-dev` there :(

in the context of https://github.com/vmware-tanzu/cartographer/issues/578, the current idea is to go with the approach of  having a separate repo for packaging (ala https://github.com/vmware-tanzu/package-for-kpack), somewhat similar to how with [concourse](https://github.com/concourse/concourse) we had [concourse-bosh-release](https://github.com/concourse/concourse-bosh-release) for bosh packaging, then [concourse-chart](https://github.com/concourse/concourse-chart) for helm, etc.

any thoughts on this approach moving forward/?

**Comment by cirocosta** [comment]
so, `vmware-tanzu/package-for-cartographer` has been created, and it's good to go in terms of producing the packages with the proper objects, but the repository is not public _yet_ - once that's done, we can then move towards removing `package*`-related things from this repository, simplifying both the dev setup and release.
