### ISSUE TITLE
Confusing description of `source` field on Deliverable

### ISSUE THREAD

**Issue by zrob** [vmware-tanzu/cartographer#649]
The source field on deliverable is described as the source of a workload, or application source. Really it is where the k8s config describing what to deploy live.

https://github.com/vmware-tanzu/cartographer/blob/edb16e9d726964babbaa13f461fc69763404d7a9/pkg/apis/v1alpha1/deliverable.go#L90-L92

**Comment by waciumawanjohi** [comment]
Is this a duplicate of #647?

**Comment by zrob** [comment]
yes. we probably grabbed it from the same source 

closing as dupe
