### ISSUE TITLE
Flakey e2e test setup

### ISSUE THREAD

**Issue by martyspiewak** [vmware-tanzu/cartographer#654]
Our e2e tests often fail on setup when trying to configure Gitea with the error: 
`Error: No such container:path: 590b0918bdfa:/data/gitea/conf` (from [here](https://github.com/vmware-tanzu/cartographer/runs/5290619320?check_suite_focus=true#step:10:509))

Once this happens we have no choice but to rerun the entire build job, which takes around a half hour to run if all goes well. This is very painful and frustrating as it delays the time it takes to get PRs merged.

**Comment by emmjohnson** [comment]
This is actively slowing us down. We have seen it on 2 PRs, multiple times this week.
