### ISSUE TITLE
Spike on Typed Supply Chains

### ISSUE THREAD

**Issue by squeedee** [vmware-tanzu/cartographer#655]
What does a supply-chain-as-a-template look like

As per this gist:
https://gist.github.com/jwntrs/9957c0e99851428b4bf52510d5902285

Some open questions to sort out:
- templates are typed outside of each option. how do we mix `Cluster(Source|Image|Config)Template` and `Cluster(Source|Image|Config)SupplyChain` types under options?
- How do we pass inputs into a nested supply chain
    - if a supply chain has a top level selector it should be useable on its own, which means it can't have undefined inputs
    - if a supply chain has undefined inputs it cannot be used as a stand alone supply chain, how do we validate it?

**Comment by jwntrs** [comment]
@martyspiewak @emmjohnson were we able to answer any of the open questions when doing this spike?

**Comment by jwntrs** [comment]
> templates are typed outside of each option. how do we mix Cluster(Source|Image|Config)Template and Cluster(Source|Image|Config)SupplyChain types under options?

I think we proved we can do this right?
