### ISSUE TITLE
Chore: Move RFCs

### ISSUE THREAD

**Issue by DanieldeR** [vmware-tanzu/cartographer#68]
Move the RFCs

- [x] Move RFCs
- [x] Fixing Boards
- [x] Move the PRs
- [x] Move the Comments for each RFC
- [x] Move milestones and tags
- [ ] if open, accepted, and rejected tags do not already exist then create them.

**Comment by waciumawanjohi** [comment]
There is a project board for the RFCs:
https://github.com/vmware-tanzu/cartographer/projects/2

**Comment by waciumawanjohi** [comment]
I know that I proposed the "open", "accepted" and "rejected" tags, but I'm not sure about them. Have not created.
