### ISSUE TITLE
R4RFC: Publishing events

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#711]
### Description of problem

Eventing in k8s is an excellent way to surface information to end users. We should use this mechanism to help surface information about whats happening in a supply chain (object stamped, output created, errors, etc). We are requesting an RFC that proposes a solution for (what/when/how/why) events to publish.

Notes:

Info/Data architecture whiteboard: https://miro.com/app/board/uXjVOD4uWt4=/

**Comment by emmjohnson** [comment]
Here is an example of an error we would like to emit - https://github.com/vmware-tanzu/cartographer/issues/589

**Comment by emmjohnson** [comment]
Things we care about eventing - Creating/updating resource, Updating status of workload, creating outputs or output changes, errors.

Events to add to supply chain if its healthy or not.

Events can aggregate. 

Users probably don't have access to logs but will have access to events. Be careful about what we event.

**Comment by emmjohnson** [comment]
Include in the RFC when to create an event or not.

**Comment by squeedee** [comment]
Data/Information architecture study: https://miro.com/app/board/uXjVOD4uWt4=/
