### ISSUE TITLE
View workload progress

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#712]
### Description of problem

How can we surface as much information as possible in the workload status so users have a better understanding of whats happening in a supply chain.

### Proposed solutions
https://github.com/vmware-tanzu/cartographer/issues/664
https://github.com/vmware-tanzu/cartographer/issues/694
https://github.com/vmware-tanzu/cartographer/issues/711

**Comment by martyspiewak** [comment]
Closing as these are now represented in our project board.
