### ISSUE TITLE
R4RFC: Artifact tracing

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#744]
### Description of problem

For a particular resource in a supply chain, we would like to be able to assert that a given input produced a specific output.

We are requesting an RFC that describes how to achieve that result using the following mechanics:

- Allow resources (via template) to define fields in their status that indicate which inputs and outputs to compare. If the input matches a specified input field, then you can trust the output (transforms input e.g. source to image)
- Allow resources (via template) to defined fields in their status that indicate which field should match a particular input (pass through input e.g. source to source).
- Allow resources (via template) to indicate that by holding spec updates we can trust a combination of the observed generation and some "healthy" status condition to know that a value in the spec produced a result in the status.

**Comment by karayim** [comment]
RFC exists
