### ISSUE TITLE
Supply chain for TCE

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#779]
Need repo in vmware-tanzu
Need to update packaging in package-for-cartographer

**Comment by scothis** [comment]
Adding a supply chain to package-for-cartographer also adds a runtime dependency on all resources stamped out by that supply chain. We should be cautious about how those dependencies are represented. Using a separate package for the supply chain would side step those questions.

**Comment by jwntrs** [comment]
@scothis yeah we definitely don't want to bundle this into the same package as cartographer. The conversation is more around should we create a separate `package-for` repo, or ship two packages alongside each other from the same repo. It's a tradeoff between fighting github release tooling vs proliferation of `package-for` repos.

I was originally under the impression that we would actually ship three packages: `carto`, `conventions`, and a `supply-chain`, but it seems like you're recommending that conventions should be include as part of cartographer itself: https://github.com/vmware-tanzu/package-for-cartographer/pull/23

**Comment by scothis** [comment]
> The conversation is more around should we create a separate `package-for` repo, or ship two packages alongside each other from the same repo.

Multiple packages from the same repo is 👍 

> I was originally under the impression that we would actually ship three packages: `carto`, `conventions`, and a `supply-chain`, but it seems like you're recommending that conventions should be include as part of cartographer itself: [vmware-tanzu/package-for-cartographer#23](https://github.com/vmware-tanzu/package-for-cartographer/pull/23)

Based on conversations with @cirocosta the PR is proposing adding conventions as a component of the existing cartographer package. We can continue that conversation on the PR.

**Comment by martyspiewak** [comment]
The repo has been created but is currently private: https://github.com/vmware-tanzu/cartographer-catalog

We will need to populate it before making it public.
