### ISSUE TITLE
Only run E2E, release and update tests when include-list directories change

### ISSUE THREAD

**Issue by squeedee** [vmware-tanzu/cartographer#843]
### Description of problem

Some folders contain documentation that should not trigger e2e
If I change an RFC, tests are triggered in GH Actions, and this leads to slow turnaround on RFC edits, and high traffic edits causing API throttling for tests.

### Proposed solution

```gherkin
Given I edit _only_ the RFC folder
When I commit and push
Then my PR for the RFC is quickly validated without running exhaustive testing
And copywrite/lint checks still run
```

**Comment by cirocosta** [comment]
I _believe_ the following should do it:

```yaml
on:
  push:
    paths-ignore:
      - "rfcs/**"
```

**Comment by squeedee** [comment]
Unfortunately we cant do this with github and also automerging dependabot. The only other solutiuon I can think of it to pull RFCs into the docs or some other repo.

**Comment by squeedee** [comment]
Discuss changing this to a "move RFCS" story.
