### ISSUE TITLE
Add age and status to CRDs.

### ISSUE THREAD

**Issue by emmjohnson** [vmware-tanzu/cartographer#90]
From PR - https://github.com/vmware-tanzu/cartographer/pull/17

Ciro's comment - 
"I usually expect to see objects to share information about their age and current highest-level status, so I usually add"

```
+kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type==\"Ready\")].status`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
```

"this is something we currently don't do for Workload and ClusterSupplyChain, but I think we should - makes the kubectl experience much better imo"

**Comment by benjaminguttmann-avtq** [comment]
@emmjohnson tried to solve this issue but have two questions:

1. Should I add the age for deliverable as well (saw that it already has status)
2. For workload and deliverable status + status reason has been added, should I add the status reason for ClusterSupplyChain as well?
