### ISSUE TITLE
Cartographer fails with ServiceAccountSecretError on k8s 1.24

### ISSUE THREAD

**Issue by idoru** [vmware-tanzu/cartographer#923]
You'll see an error like this:

```
Status:
  Conditions:
    Last Transition Time:  2022-06-23T07:27:06Z
    Message:
    Reason:                Ready
    Status:                True
    Type:                  SupplyChainReady
    Last Transition Time:  2022-06-23T07:27:06Z
    Message:               service account [my-apps/default] does not have any token secrets
    Reason:                ServiceAccountSecretError
    Status:                False
    Type:                  ResourcesSubmitted
    Last Transition Time:  2022-06-23T07:27:06Z
    Message:               service account [my-apps/default] does not have any token secrets
    Reason:                ServiceAccountSecretError
    Status:                False
    Type:                  Ready
  Observed Generation:     1
  Supply Chain Ref:
    Kind:  ClusterSupplyChain
    Name:  source-to-url
Events:    <none> 
```

This is because in k8s 1.24:

- Secrets are not automatically created for ServiceAccounts 
- ServiceAccounts no longer list their Secrets

We should instead obtain tokens as necessary using the Token API which is the recommended way from the deprecation.

A similar issue occurred with `carvel-kapp-controller`:
(Link to Issue)[https://github.com/vmware-tanzu/carvel-kapp-controller/issues/687]
(Link to Fix)[https://github.com/vmware-tanzu/carvel-kapp-controller/pull/695]

**Comment by cirocosta** [comment]
on testing, we might be able to add a test matrix for 1.24 & 1.23 by tweaking

```console
# hack/setup.sh
25:readonly KIND_IMAGE=${KIND_IMAGE:-kindest/node:v1.21.1}
169:    KIND_IMAGE:     $KIND_IMAGE
213:    image: ${KIND_IMAGE}
```

see https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#using-a-matrix-strategy
