### ISSUE TITLE
GitWritter with Tekton Example

### ISSUE THREAD

**Issue by DanieldeR** [vmware-tanzu/cartographer#99]
A current gap that exists is the ability to write to a git repository. The purpose of this issue is to create an example supply chain with the last step leveraging the pipeline service and Tekton to write some YAML to a git repository.

## Acceptance Criteria
An example exists where:
* A supply chain writes some yaml (likely a knative service wrapped in a Kapp App) to a git repository
* Usage of the supply chain is documented in both OSS and Commericial docs

**Note** While we may eventually need the ability to specify the git repository in the workload, for now having the operator hard code it in a Tekton pipeline is sufficient.

**Comment by squeedee** [comment]
Leaving open as it gets rolled into #405
